import { AmbitionData, AmbitionMilestone, AmbitionTask } from "@/types";

export interface ExampleAmbitionType {
    category: string;
    examples: {
        ambition: AmbitionData,
        tasks?: AmbitionTask[],
        milestones?: AmbitionMilestone[]
    }[];
}

const exampleAmbitions: ExampleAmbitionType[] = [
    // Personal Development
    {
        category: "Personal Growth",
        examples: [
            {
                ambition: {
                    id: "1",
                    userId: "1",
                    ambitionName: "Learn to play the piano and perform at a local venue",
                    ambitionDefinition: "Learn to play the piano and perform at a local venue",
                    ambitionTrackingMethod: "milestone",
                    ambitionSuccessMetric: "",
                    ambitionStartDate: null,
                    ambitionEndDate: null,
                    ambitionCompletionDate: null,
                    ambitionDeadline: "2024-12-31",
                    ambitionStatus: "active",
                    ambitionPriority: "high",
                    ambitionCategory: "Personal Growth",
                    ambitionPercentageCompleted: 0,
                    ambitionColor: "#FF5733",
                    createdAt: new Date(),
                    updatedAt: new Date(),
                    isFavourited: false,
                },
                milestones: [{
                    id: "1",
                    userId: "1",
                    ambitionId: "1",
                    milestone: "Learn the basics of piano",
                    milestoneDescription: "Complete a beginner's piano course",
                    milestoneCompleted: false,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                    milestoneTargetDate: new Date("2024-06-30"),
                }],
            },
            {
                ambition: {
                    id: "2",
                    userId: "1",
                    ambitionName: "Master conversational Spanish in 6 months",
                    ambitionDefinition: "Master conversational Spanish in 6 months",
                    ambitionTrackingMethod: "milestone",
                    ambitionSuccessMetric: "",
                    ambitionStartDate: null,
                    ambitionEndDate: null,
                    ambitionCompletionDate: null,
                    ambitionDeadline: "2026-05-15",
                    ambitionStatus: "active",
                    ambitionPriority: "medium",
                    ambitionCategory: "Personal Growth",
                    ambitionPercentageCompleted: 0,
                    ambitionColor: "#3498DB",
                    createdAt: new Date(),
                    updatedAt: new Date(),
                    isFavourited: false,
                },
                milestones: [],
            },
            {
                ambition: {
                    id: "3",
                    userId: "1",
                    ambitionName: "Complete a 30-day meditation challenge",
                    ambitionDefinition: "Complete a 30-day meditation challenge",
                    ambitionTrackingMethod: "milestone",
                    ambitionSuccessMetric: "",
                    ambitionStartDate: null,
                    ambitionEndDate: null,
                    ambitionCompletionDate: null,
                    ambitionDeadline: "2026-05-15",
                    ambitionStatus: "active",
                    ambitionPriority: "medium",
                    ambitionCategory: "Personal Growth",
                    ambitionPercentageCompleted: 0,
                    ambitionColor: "#2ECC71",
                    createdAt: new Date(),
                    updatedAt: new Date(),
                    isFavourited: false,
                },
                milestones: [],
            },
        ],
    },
    // Career & Business
    {
        category: "Career & Business",
        examples: [
            {
                ambition: {
                    id: "4",
                    userId: "1",
                    ambitionName: "Launch my first tech startup within 12 months",
                    ambitionDefinition: "Launch my first tech startup within 12 months",
                    ambitionTrackingMethod: "milestone",
                    ambitionSuccessMetric: "",
                    ambitionStartDate: null,
                    ambitionEndDate: null,
                    ambitionCompletionDate: null,
                    ambitionDeadline: "2026-05-15",
                    ambitionStatus: "active",
                    ambitionPriority: "high",
                    ambitionCategory: "Career & Business",
                    ambitionPercentageCompleted: 0,
                    ambitionColor: "#F1C40F",
                    createdAt: new Date(),
                    updatedAt: new Date(),
                    isFavourited: false,
                },
                milestones: [],
            },
            {
                ambition: {
                    id: "5",
                    userId: "1",
                    ambitionName: "Complete my MBA while working full-time",
                    ambitionDefinition: "Complete my MBA while working full-time",
                    ambitionTrackingMethod: "milestone",
                    ambitionSuccessMetric: "",
                    ambitionStartDate: null,
                    ambitionEndDate: null,
                    ambitionCompletionDate: null,
                    ambitionDeadline: "2026-05-15",
                    ambitionStatus: "active",
                    ambitionPriority: "medium",
                    ambitionCategory: "Career & Business",
                    ambitionPercentageCompleted: 0,
                    ambitionColor: "#9B59B6",
                    createdAt: new Date(),
                    updatedAt: new Date(),
                    isFavourited: false,
                },
                milestones: [],
            },
            {
                ambition: {
                    id: "6",
                    userId: "1",
                    ambitionName: "Build a portfolio of 10 successful client projects",
                    ambitionDefinition: "Build a portfolio of 10 successful client projects",
                    ambitionTrackingMethod: "milestone",
                    ambitionSuccessMetric: "",
                    ambitionStartDate: null,
                    ambitionEndDate: null,
                    ambitionCompletionDate: null,
                    ambitionDeadline: "2026-05-15",
                    ambitionStatus: "active",
                    ambitionPriority: "medium",
                    ambitionCategory: "Career & Business",
                    ambitionPercentageCompleted: 0,
                    ambitionColor: "#E74C3C",
                    createdAt: new Date(),
                    updatedAt: new Date(),
                    isFavourited: false,
                },
                milestones: [],
            },
        ],
    },
    // Health & Fitness
    {
        category: "Health & Fitness",
        examples: [
            {
                ambition: {
                    id: "7",
                    userId: "1",
                    ambitionName: "Run a marathon in under 4 hours",
                    ambitionDefinition: "Run a marathon in under 4 hours",
                    ambitionTrackingMethod: "milestone",
                    ambitionSuccessMetric: "",
                    ambitionStartDate: null,
                    ambitionEndDate: null,
                    ambitionCompletionDate: null,
                    ambitionDeadline: "2026-05-15",
                    ambitionStatus: "active",
                    ambitionPriority: "high",
                    ambitionCategory: "Health & Fitness",
                    ambitionPercentageCompleted: 0,
                    ambitionColor: "#1ABC9C",
                    createdAt: new Date(),
                    updatedAt: new Date(),
                    isFavourited: false,
                },
                milestones: [],
            },
            {
                ambition: {
                    id: "8",
                    userId: "1",
                    ambitionName: "Achieve a consistent 5am morning routine",
                    ambitionDefinition: "Achieve a consistent 5am morning routine",
                    ambitionTrackingMethod: "milestone",
                    ambitionSuccessMetric: "",
                    ambitionStartDate: null,
                    ambitionEndDate: null,
                    ambitionCompletionDate: null,
                    ambitionDeadline: "2026-05-15",
                    ambitionStatus: "active",
                    ambitionPriority: "medium",
                    ambitionCategory: "Health & Fitness",
                    ambitionPercentageCompleted: 0,
                    ambitionColor: "#E67E22",
                    createdAt: new Date(),
                    updatedAt: new Date(),
                    isFavourited: false,
                },
                milestones: [],
            },
            {
                ambition: {
                    id: "9",
                    userId: "1",
                    ambitionName: "Complete a 100-day fitness transformation",
                    ambitionDefinition: "Complete a 100-day fitness transformation",
                    ambitionTrackingMethod: "milestone",
                    ambitionSuccessMetric: "",
                    ambitionStartDate: null,
                    ambitionEndDate: null,
                    ambitionCompletionDate: null,
                    ambitionDeadline: "2026-05-15",
                    ambitionStatus: "active",
                    ambitionPriority: "medium",
                    ambitionCategory: "Health & Fitness",
                    ambitionPercentageCompleted: 0,
                    ambitionColor: "#FF5733", // Repeating color from palette
                    createdAt: new Date(),
                    updatedAt: new Date(),
                    isFavourited: false,
                },
                milestones: [],
            },
        ],
    },
];

export default exampleAmbitions;